--USE O DB
USE CONTROLE_VENDAS
;
GO

--SELECIONAR A TABELA VENDAS
SELECT * FROM VENDAS
;
GO

--SELECIONAR A TABELA PRODUTO
SELECT * FROM PRODUTO
;
GO

--SELECIONAR A TABELA VENDEDOR
SELECT * FROM VENDEDOR
;
GO

--SELECIONAR A TABELA CLIENTE
SELECT * FROM CLIENTE
;
GO

--SELECIONAR A TABELA REGIAO
SELECT * FROM REGIAO
;
GO

--SOMAR(CALCULAR) O TOTAL DE VENDAS DO MÊS
SELECT SUM(QTD_VENDIDA * PRECO_VENDA) AS TOTAL_GERAL FROM VENDAS
;
GO

--CALCULAR O PERCENTUAL DE VENDAS POR VENDEDOR
SELECT 
	FK_VENDEDOR,
	SUM(QTD_VENDIDA * PRECO_VENDA) AS TOTAL_SEG,
	ROUND((SUM(QTD_VENDIDA * PRECO_VENDA) / (SELECT SUM(QTD_VENDIDA * PRECO_VENDA) AS TOTAL_GERAL FROM VENDAS)) * 100,2) AS TOTAL_GERAL
FROM VENDAS
GROUP BY FK_VENDEDOR
ORDER BY TOTAL_GERAL DESC
;
GO

--CALCULAR O PERCENTUAL DE VENDAS COM NOME VENDEDOR E PRODUTO
SELECT 
	P.NOME_PRODUTO,
	VE.NOME_VENDEDOR,
	CONVERT(DATE,V.DATA) AS DATA_VENDA,
	SUM(QTD_VENDIDA * PRECO_VENDA) AS TOTAL_SEG,
	ROUND((
		SUM(QTD_VENDIDA * PRECO_VENDA) / 
		(SELECT SUM(QTD_VENDIDA * PRECO_VENDA) AS TOTAL_GERAL FROM VENDAS)) * 100,2) AS TOTAL_GERAL
FROM VENDAS V
INNER JOIN VENDEDOR VE ON V.FK_VENDEDOR = VE.ID_VENDEDOR
INNER JOIN PRODUTO P ON P.ID_PRODUTO = V.FK_PRODUTO
WHERE MONTH(V.DATA) = 01
GROUP BY VE.NOME_VENDEDOR, P.NOME_PRODUTO
ORDER BY P.NOME_PRODUTO ASC
;
GO

--CALCULAR O PERCENTUAL DE VENDAS COM NOME VENDEDOR E PRODUTO
SELECT 
	P.NOME_PRODUTO,
	VE.NOME_VENDEDOR,
	SUM(QTD_VENDIDA * PRECO_VENDA) AS TOTAL_GERAL
FROM VENDAS V
INNER JOIN VENDEDOR VE ON V.FK_VENDEDOR = VE.ID_VENDEDOR
INNER JOIN PRODUTO P ON P.ID_PRODUTO = V.FK_PRODUTO
GROUP BY P.NOME_PRODUTO, VE.NOME_VENDEDOR
ORDER BY P.NOME_PRODUTO, VE.NOME_VENDEDOR ASC
;
GO

--USANDO CTE COM OVER PARTITION
WITH CTE_A AS(
SELECT 
	P.NOME_PRODUTO AS NOME_PRODUTO,
	VE.NOME_VENDEDOR AS NOME_VENDEDOR,
	SUM(V.QTD_VENDIDA * V.PRECO_VENDA) AS TOTAL_GERAL,
	SUM(O.QTD_ORCADA * O.PRECO_VENDA) AS TOTAL_ORCADA
FROM VENDAS V
INNER JOIN VENDEDOR VE ON V.FK_VENDEDOR = VE.ID_VENDEDOR
INNER JOIN PRODUTO P ON P.ID_PRODUTO = V.FK_PRODUTO
INNER JOIN CONTROLE_ORCAMENTO.dbo.ORCAMENTO O ON O.FK_PRODUTO = V.FK_PRODUTO
GROUP BY P.NOME_PRODUTO, VE.NOME_VENDEDOR
), CTE_B AS (
SELECT 
	NOME_PRODUTO, 
	NOME_VENDEDOR,
	TOTAL_GERAL,
	TOTAL_ORCADA,
	SUM(TOTAL_GERAL) OVER(PARTITION BY NOME_PRODUTO) AS TOTAL_POR_PRODUTO
FROM CTE_A
GROUP BY NOME_PRODUTO, NOME_VENDEDOR, TOTAL_GERAL, TOTAL_ORCADA
), CTE_C AS (
SELECT
	NOME_PRODUTO, 
	NOME_VENDEDOR,
	TOTAL_GERAL,
	TOTAL_ORCADA,
	(TOTAL_GERAL / TOTAL_POR_PRODUTO) AS PERC_PRODUTO
	--(PERC_PRODUTO * TOTAL_ORCADO) AS TOTAL_OBJETIVO
FROM CTE_B
)
SELECT 
	NOME_PRODUTO, 
	NOME_VENDEDOR,
	TOTAL_GERAL,
	TOTAL_ORCADA,
	--(TOTAL_GERAL / TOTAL_POR_PRODUTO) AS PERC_PRODUTO,
	ROUND((PERC_PRODUTO * TOTAL_ORCADA),2) AS TOTAL_OBJETIVO
FROM CTE_C
ORDER BY NOME_PRODUTO, NOME_VENDEDOR ASC
;
GO

INSERT INTO VENDAS(FK_CLIENTE,FK_PRODUTO,QTD_VENDIDA,PRECO_VENDA,FK_VENDEDOR,DATA,FK_REGIAO,DESCONTO)
VALUES(100,6,200,264.71,1,getdate(),17,0.03)
;
GO

/* CONSTRUINDO ALGUMAS CTEs PARA AJUSTAR O DW */

--SELECIONAR A TABELA VENDAS
SELECT 
	V.ID_VENDAS,
	C.NOME_CLIENTE,
	P.NOME_PRODUTO,
	QTD_VENDIDA,
	PRECO_VENDA,
	VE.NOME_VENDEDOR,
	DATA,
	R.SIGLA_ESTADO,
	DESCONTO
FROM VENDAS V
INNER JOIN CLIENTE C ON C.ID_CLIENTE = V.FK_CLIENTE
INNER JOIN PRODUTO P ON P.ID_PRODUTO = V.FK_PRODUTO
INNER JOIN VENDEDOR VE ON VE.ID_VENDEDOR = V.FK_VENDEDOR
INNER JOIN REGIAO R ON R.ID_REGIAO = V.FK_REGIAO
;
GO